#pragma once

#define MAT_SPRITE "Sprite"
#define MAT_LAYERCOLOR "LayerColor"
#define MAT_LABEL "Label"
#define MAT_SKYBOX "Skybox"
#define MAT_MODEL "Model"
#define MAT_MODEL_SHADOW "ModelShadow"
#define MAT_BLOOM "Bloom"
#define MAT_BOX_BLUR "BoxBlur"
#define MAT_SSAO "HorizonBasedAO"
#define MAT_PAINT "Paint3D"
#define MAT_LINE_PAINT "LinePaint3D"

#define LIGHTMODE_SHADOW_CASTER "ShadowCaster"
#define LIGHTMODE_FORWARD_BASE "ForwardBase"
#define LIGHTMODE_FORWARD_ADD "ForwardAdd"
#define LIGHTMODE_POSTPROCESS "PostProcess"
#define LIGHTMODE_PREPASS_BASE "PrepassBase"
#define LIGHTMODE_PREPASS_FINAL "PrepassFinal"
#define LIGHTMODE_TRANSPARENT "Transparent"
#define LIGHTMODE_SKYBOX "Skybox"
#define LIGHTMODE_OVERLAY "Overlay"