#pragma once

namespace mir {

enum PrimitiveTopology 
{
	kPrimTopologyUnkown = 0,
	kPrimTopologyPointList = 1,
	kPrimTopologyLineList = 2,
	kPrimTopologyLineStrip = 3,
	kPrimTopologyTriangleList = 4,
	kPrimTopologyTriangleStrip = 5,
	kPrimTopologyLineListAdj = 10,
	kPrimTopologyLineStripAdj = 11,
	kPrimTopologyTriangleListAdj = 12,
	kPrimTopologyTriangleStripAdj = 13,
	kPrimTopology1CtrlPointPatchList = 33,
	kPrimTopology2CtrlPointPatchList = 34,
	kPrimTopology3CtrlPointPatchList = 35,
	kPrimTopology4CtrlPointPatchList = 36,
	kPrimTopology5CtrlPointPatchList = 37,
	kPrimTopology6CtrlPointPatchList = 38,
	kPrimTopology7CtrlPointPatchList = 39,
	kPrimTopology8CtrlPointPatchList = 40,
	kPrimTopology9CtrlPointPatchList = 41,
	kPrimTopology10CtrlPointPatchList = 42,
	kPrimTopology11CtrlPointPatchList = 43,
	kPrimTopology12CtrlPointPatchList = 44,
	kPrimTopology13CtrlPointPatchList = 45,
	kPrimTopology14CtrlPointPatchList = 46,
	kPrimTopology15CtrlPointPatchList = 47,
	kPrimTopology16CtrlPointPatchList = 48,
	kPrimTopology17CtrlPointPatchList = 49,
	kPrimTopology18CtrlPointPatchList = 50,
	kPrimTopology19CtrlPointPatchList = 51,
	kPrimTopology20CtrlPointPatchList = 52,
	kPrimTopology21CtrlPointPatchList = 53,
	kPrimTopology22CtrlPointPatchList = 54,
	kPrimTopology23CtrlPointPatchList = 55,
	kPrimTopology24CtrlPointPatchList = 56,
	kPrimTopology25CtrlPointPatchList = 57,
	kPrimTopology26CtrlPointPatchList = 58,
	kPrimTopology27CtrlPointPatchList = 59,
	kPrimTopology28CtrlPointPatchList = 60,
	kPrimTopology29CtrlPointPatchList = 61,
	kPrimTopology30CtrlPointPatchList = 62,
	kPrimTopology31CtrlPointPatchList = 63,
	kPrimTopology32CtrlPointPatchList = 64,
};

}